export const DB = {
  profiles: "hamster_profiles",
  studies: "hamster_studies",
  studyMembers: "hamster_study_members",
  studyRuleVersions: "hamster_study_rule_versions",
  githubInstallations: "hamster_github_installations",
  repositoryConnections: "hamster_repository_connections",
  problems: "hamster_problems",
  submissions: "hamster_submissions",
  postponements: "hamster_postponements",
  penalties: "hamster_penalties",
  webhookEvents: "hamster_webhook_events",
  pushSubscriptions: "hamster_push_subscriptions",
  notificationPreferences: "hamster_notification_preferences",
  notificationDeliveries: "hamster_notification_deliveries",
} as const;
