"use client";

import { useEffect, useMemo, useState } from "react";
import { browserSupabase } from "@/lib/supabase-browser";
import { GrowthStatsSection, invalidateGrowthStatsCache } from "./growth-stats-section";

type Repo={id:string;fullName:string};
type Submission={platform:string;problemId:string;title:string;difficulty:string;credit:number;solvedAt:string;source:string};
type MemberState="inactive"|"upcoming"|"presolved"|"complete"|"in-progress"|"postponed"|"missed";
type DayMember={userId:string;name:string;state:MemberState;credits:number;directCredits:number;penalty:number;consecutiveMisses:number;postponedAt:string|null;submissions:Submission[]};
type CalendarDay={date:string;members:DayMember[]};
type RuleConfig={bojBronzeCount:number;bojSilverCount:number;bojGoldCount:number;programmersLowCount:number;programmersHighCount:number;sweaLowCount:number;sweaHighCount:number;codetreeSamsungCount:number;penalties:{1:number;2:number;3:number}};
type Study={id:string;name:string;inviteCode:string;role:"admin"|"member";rules:RuleConfig;postponeDeadlineHour:number;postponeDeadlineMinute:number;maxConsecutivePostpone:number;maxPresolveDays:number};
type MemberStat={userId:string;name:string;complete:number;missed:number;postponed:number;totalPenalty:number;completionRate:number;streak:number};
type RuleHistory={effectiveFrom:string;changedBy:string;createdAt:string|null};
type DashboardData={study:Study|null;members:Array<{userId:string;name:string}>;repositories:Repo[];days:CalendarDay[];summary:{complete:number;postponed:number;missed:number;inProgress:number};statistics:MemberStat[];ruleHistory:RuleHistory[];currentUserId:string;studyDate:string;month:string};
type RulesDraft={ruleConfig:RuleConfig;postponeDeadlineHour:number;postponeDeadlineMinute:number;maxConsecutivePostpone:number;maxPresolveDays:number};
type InstallPromptEvent=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:"accepted"|"dismissed"}>};
type ManualPlatform="BOJ"|"PROGRAMMERS"|"SWEA"|"CODETREE";

type DifficultyOption={label:string;value:string};
const MANUAL_DIFFICULTIES:Record<ManualPlatform,DifficultyOption[]>={
  BOJ:[{label:"Bronze II~I",value:"Bronze I"},{label:"Silver V~I",value:"Silver III"},{label:"Gold 이상",value:"Gold V"}],
  PROGRAMMERS:[{label:"Lv.0~1",value:"Level 1"},{label:"Lv.2 이상",value:"Level 2"}],
  SWEA:[{label:"D2~D3",value:"D3"},{label:"D4 이상",value:"D4"}],
  CODETREE:[{label:"삼성 기출",value:"SAMSUNG"}],
};
const PLATFORM_LABEL:Record<ManualPlatform,string>={BOJ:"Baekjoon",PROGRAMMERS:"Programmers",SWEA:"SWEA",CODETREE:"CodeTree"};
const STATE_META:Record<MemberState,{icon:string;label:string}>={complete:{icon:"✅",label:"완료"},presolved:{icon:"●",label:"선풀이"},"in-progress":{icon:"🟡",label:"진행 중"},postponed:{icon:"⏭",label:"미루기"},missed:{icon:"❌",label:"미제출"},upcoming:{icon:"·",label:"예정"},inactive:{icon:"",label:"참여 전"}};
const WEEKDAYS=["일","월","화","수","목","금","토"];

async function accessToken(){const{data}=await browserSupabase().auth.getSession();return data.session?.access_token;}
function formatMonth(month:string){const[y,m]=month.split("-");return`${y}년 ${Number(m)}월`;}
function shiftMonth(month:string,delta:number){const[y,m]=month.split("-").map(Number);const d=new Date(Date.UTC(y,m-1+delta,1));return`${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,"0")}`;}
function formatDateHeading(date:string){const d=new Date(`${date}T00:00:00Z`);const weekday=new Intl.DateTimeFormat("ko-KR",{weekday:"long",timeZone:"UTC"}).format(d);const[,m,day]=date.split("-");return`${Number(m)}월 ${Number(day)}일 ${weekday}`;}
function formatTime(value:string|null){if(!value)return"";return new Intl.DateTimeFormat("ko-KR",{timeZone:"Asia/Seoul",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(value));}
function formatDeadline(h:number,m:number){return`${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}`;}
function calendarSlots(month:string){const[y,m]=month.split("-").map(Number);const first=new Date(Date.UTC(y,m-1,1));const firstWeekday=first.getUTCDay();const daysInMonth=new Date(Date.UTC(y,m,0)).getUTCDate();return Array.from({length:42},(_,i)=>{const day=i-firstWeekday+1;const d=new Date(Date.UTC(y,m-1,day));return{date:d.toISOString().slice(0,10),currentMonth:day>=1&&day<=daysInMonth};});}
function cloneRules(study:Study):RulesDraft{return{ruleConfig:{...study.rules,penalties:{...study.rules.penalties}},postponeDeadlineHour:study.postponeDeadlineHour,postponeDeadlineMinute:study.postponeDeadlineMinute,maxConsecutivePostpone:study.maxConsecutivePostpone,maxPresolveDays:study.maxPresolveDays};}
function NumberField({label,value,min=0,max=20,suffix,onChange}:{label:string;value:number;min?:number;max?:number;suffix:string;onChange:(value:number)=>void}){return<label className="rule-field"><span>{label}</span><div><input type="number" min={min} max={max} value={value} onChange={e=>onChange(Number(e.target.value))}/><em>{suffix}</em></div></label>}

export function Dashboard({githubAppSlug}:{githubAppSlug:string}){
  const[data,setData]=useState<DashboardData|null>(null);const[error,setError]=useState("");const[busy,setBusy]=useState("");const[month,setMonth]=useState("");const[selectedDate,setSelectedDate]=useState("");
  const[settingsOpen,setSettingsOpen]=useState(false);const[detailOpen,setDetailOpen]=useState(false);const[rulesDraft,setRulesDraft]=useState<RulesDraft|null>(null);const[toast,setToast]=useState("");
  const[tab,setTab]=useState<"calendar"|"stats">("calendar");const[calendarMode,setCalendarMode]=useState<"month"|"week">("month");const[joinCode,setJoinCode]=useState("");
  const[installPrompt,setInstallPrompt]=useState<InstallPromptEvent|null>(null);const[showInstall,setShowInstall]=useState(false);const[iosInstall,setIosInstall]=useState(false);
  const[manualOpen,setManualOpen]=useState(false);const[manualPlatform,setManualPlatform]=useState<ManualPlatform>("BOJ");const[manualDifficulty,setManualDifficulty]=useState(MANUAL_DIFFICULTIES.BOJ[1].value);const[manualCount,setManualCount]=useState(1);

  async function reload(targetMonth?:string){const access=await accessToken();if(!access){window.location.replace("/");return;}const q=targetMonth?`?month=${encodeURIComponent(targetMonth)}`:"";const r=await fetch(`/api/dashboard${q}`,{headers:{Authorization:`Bearer ${access}`}});const p=await r.json() as DashboardData&{error?:string};if(!r.ok){setError(p.error??"조회 실패");return;}setError("");setData(p);setMonth(p.month);if(!selectedDate||!selectedDate.startsWith(p.month))setSelectedDate(p.studyDate.startsWith(p.month)?p.studyDate:`${p.month}-01`);}

  useEffect(()=>{let cancelled=false;void(async()=>{const access=await accessToken();if(!access){window.location.replace("/");return;}const r=await fetch("/api/dashboard",{headers:{Authorization:`Bearer ${access}`}});const p=await r.json() as DashboardData&{error?:string};if(cancelled)return;if(!r.ok){setError(p.error??"조회 실패");return;}setData(p);setMonth(p.month);setSelectedDate(p.studyDate.startsWith(p.month)?p.studyDate:`${p.month}-01`);})();return()=>{cancelled=true}},[]);
  useEffect(()=>{if(!toast)return;const id=window.setTimeout(()=>setToast(""),2800);return()=>window.clearTimeout(id)},[toast]);
  useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==="Escape"){setDetailOpen(false);setSettingsOpen(false);setManualOpen(false)}};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[]);
  useEffect(()=>{const standalone=window.matchMedia("(display-mode: standalone)").matches||Boolean((navigator as Navigator&{standalone?:boolean}).standalone);if(standalone||localStorage.getItem("hamster-install-dismissed")==="1")return;const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);const timer=window.setTimeout(()=>{setIosInstall(ios);if(ios)setShowInstall(true)},0);const handler=(event:Event)=>{event.preventDefault();setInstallPrompt(event as InstallPromptEvent);setShowInstall(true)};window.addEventListener("beforeinstallprompt",handler);return()=>{window.clearTimeout(timer);window.removeEventListener("beforeinstallprompt",handler)}},[]);

  async function createStudy(){setBusy("create");const access=await accessToken();const r=await fetch("/api/studies",{method:"POST",headers:{Authorization:`Bearer ${access}`,"Content-Type":"application/json"},body:JSON.stringify({name:"햄쮸터"})});setBusy("");if(r.ok)await reload();else setToast("스터디를 만들지 못했습니다.")}
  async function joinStudy(){if(!joinCode.trim())return;setBusy("join");const access=await accessToken();const r=await fetch("/api/studies/join",{method:"POST",headers:{Authorization:`Bearer ${access}`,"Content-Type":"application/json"},body:JSON.stringify({code:joinCode.trim()})});const p=await r.json() as{error?:string};setBusy("");if(!r.ok)setToast(p.error??"스터디 참여에 실패했습니다.");else await reload()}
  function openSettings(){if(data?.study)setRulesDraft(cloneRules(data.study));setSettingsOpen(true)}
  function connect(){if(!data?.study)return;if(!githubAppSlug){setToast("GitHub App 설정이 아직 연결되지 않았습니다.");return;}localStorage.setItem("hamster-study-id",data.study.id);window.location.href=`https://github.com/apps/${githubAppSlug}/installations/new`}
  async function postpone(){if(!data?.study||selectedDate!==data.studyDate)return;setBusy("postpone");const access=await accessToken();const r=await fetch("/api/postponements",{method:"POST",headers:{Authorization:`Bearer ${access}`,"Content-Type":"application/json"},body:JSON.stringify({studyId:data.study.id})});const p=await r.json() as{error?:string;duplicate?:boolean};setBusy("");if(!r.ok)setToast(p.error??"미루기 신청에 실패했습니다.");else{setToast(p.duplicate?"이미 오늘 미루기를 신청했습니다.":"오늘 미루기를 적용했습니다.");await reload(month)}}
  async function backfill(repo:Repo){if(!data?.study)return;setBusy(repo.id);const access=await accessToken();const r=await fetch("/api/repositories/backfill",{method:"POST",headers:{Authorization:`Bearer ${access}`,"Content-Type":"application/json"},body:JSON.stringify({connectionId:repo.id})});const p=await r.json() as{error?:string;inserted?:number};setBusy("");if(!r.ok)setToast(p.error??"과거 기록을 가져오지 못했습니다.");else{invalidateGrowthStatsCache(data.currentUserId,data.study.id);setToast(`${p.inserted??0}개 풀이를 가져왔습니다.`);await reload(month)}}
  async function saveRules(){if(!data?.study||!rulesDraft)return;setBusy("rules");const access=await accessToken();const r=await fetch("/api/studies/settings",{method:"PATCH",headers:{Authorization:`Bearer ${access}`,"Content-Type":"application/json"},body:JSON.stringify({studyId:data.study.id,...rulesDraft})});const p=await r.json() as{error?:string;effectiveFrom?:string};setBusy("");if(!r.ok){setToast(p.error??"규칙을 저장하지 못했습니다.");return;}setToast(`${p.effectiveFrom??"오늘"}부터 새 규칙을 적용합니다.`);await reload(month)}
  async function addManualSubmission(){if(!data?.study||selectedDate>data.studyDate)return;setBusy("manual");const access=await accessToken();const r=await fetch("/api/submissions/manual",{method:"POST",headers:{Authorization:`Bearer ${access}`,"Content-Type":"application/json"},body:JSON.stringify({studyId:data.study.id,studyDate:selectedDate,platform:manualPlatform,difficulty:manualDifficulty,count:manualCount})});const p=await r.json() as{error?:string;inserted?:number};setBusy("");if(!r.ok){setToast(p.error??"수동 인증을 등록하지 못했습니다.");return;}invalidateGrowthStatsCache(data.currentUserId,data.study.id);setToast(`${p.inserted??manualCount}문제를 수동 인증으로 등록했습니다.`);setManualOpen(false);await reload(month)}
  async function copyInvite(){if(!data?.study)return;await navigator.clipboard.writeText(`${window.location.origin}/join/${data.study.inviteCode}`);setToast("초대 링크를 복사했습니다.")}
  async function logout(){await browserSupabase().auth.signOut();localStorage.removeItem("hamster-study-id");window.location.replace("/")}
  async function moveMonth(delta:number){const next=shiftMonth(month,delta);setDetailOpen(false);setManualOpen(false);await reload(next)}
  async function goToday(){if(!data)return;await reload(data.studyDate.slice(0,7));setSelectedDate(data.studyDate);setDetailOpen(true);setManualOpen(false)}
  async function openDate(date:string,currentMonth:boolean){if(!currentMonth)await reload(date.slice(0,7));setSelectedDate(date);setDetailOpen(true);setManualOpen(false)}
  async function installApp(){if(installPrompt){await installPrompt.prompt();const choice=await installPrompt.userChoice;if(choice.outcome==="accepted")setShowInstall(false)}else if(iosInstall)setToast("Safari 공유 버튼 → 홈 화면에 추가 → 웹 앱으로 열기를 선택하세요.")}
  function dismissInstall(){localStorage.setItem("hamster-install-dismissed","1");setShowInstall(false)}
  function changeManualPlatform(platform:ManualPlatform){setManualPlatform(platform);setManualDifficulty(MANUAL_DIFFICULTIES[platform][0].value)}

  const dayByDate=useMemo(()=>new Map((data?.days??[]).map(d=>[d.date,d])),[data]);const slots=useMemo(()=>(month?calendarSlots(month):[]),[month]);
  const visibleSlots=useMemo(()=>{if(calendarMode==="month"||!selectedDate)return slots;const i=slots.findIndex(s=>s.date===selectedDate);const start=i<0?0:Math.floor(i/7)*7;return slots.slice(start,start+7)},[calendarMode,selectedDate,slots]);
  const selectedDay=selectedDate?dayByDate.get(selectedDate):undefined;const mySelectedState=selectedDay?.members.find(m=>m.userId===data?.currentUserId);

  if(error)return<main className="app-shell"><div className="empty-state"><strong>대시보드를 불러오지 못했습니다.</strong><p>{error}</p><button className="secondary-button" onClick={()=>void reload(month)}>다시 시도</button></div></main>;
  if(!data)return<main className="app-shell"><div className="loading-state">햄쮸터를 불러오는 중…</div></main>;
  if(!data.study)return<main className="app-shell"><section className="onboarding onboarding-card"><span className="eyebrow">WELCOME TO HAMJJUTER</span><h1>스터디만 고르면<br/>자동 인증 준비 끝.</h1><p>새 스터디를 만들거나 받은 초대 코드로 바로 참여할 수 있습니다.</p><div className="onboarding-actions"><button className="primary-button" onClick={()=>void createStudy()} disabled={busy==="create"}>{busy==="create"?"만드는 중…":"새 스터디 만들기"}</button><div className="join-box"><input value={joinCode} onChange={e=>setJoinCode(e.target.value)} placeholder="초대 코드 입력" aria-label="스터디 초대 코드"/><button className="secondary-button" onClick={()=>void joinStudy()} disabled={busy==="join"}>{busy==="join"?"참여 중…":"참여하기"}</button></div></div></section></main>;

  const study=data.study;const editableRules=rulesDraft??cloneRules(study);const needsRepository=data.repositories.length===0;
  const calendarView=<><section className="calendar-toolbar"><div className="month-navigation"><button className="nav-button" onClick={()=>void moveMonth(-1)}>‹</button><h2>{formatMonth(month)}</h2><button className="nav-button" onClick={()=>void moveMonth(1)}>›</button><button className="today-button" onClick={()=>void goToday()}>오늘</button><div className="view-toggle"><button className={calendarMode==="week"?"active":""} onClick={()=>setCalendarMode("week")}>주</button><button className={calendarMode==="month"?"active":""} onClick={()=>setCalendarMode("month")}>월</button></div></div><div className="summary-strip"><span><strong>{data.members.length}</strong>명</span><span><strong>{data.summary.complete}</strong> 완료</span><span><strong>{data.summary.postponed}</strong> 미루기</span><span><strong>{data.summary.missed}</strong> 미제출</span></div></section><section className={`calendar-card mode-${calendarMode}`}><div className="weekday-row">{WEEKDAYS.map(d=><div key={d}>{d}</div>)}</div><div className="calendar-grid">{visibleSlots.map(slot=>{const day=dayByDate.get(slot.date);const today=slot.date===data.studyDate;const selected=slot.date===selectedDate;return<button key={slot.date} className={`calendar-day${slot.currentMonth?"":" is-adjacent"}${today?" is-today":""}${selected?" is-selected":""}`} onClick={()=>void openDate(slot.date,slot.currentMonth)} aria-pressed={selected}><div className="day-heading"><span>{Number(slot.date.slice(-2))}</span>{today&&<em>오늘</em>}</div><div className="day-members">{(day?.members??[]).filter(m=>m.state!=="inactive").map(m=>{const meta=STATE_META[m.state];return<div key={m.userId} className={`member-chip state-${m.state}`} title={`${m.name} · ${meta.label}`}><span className="member-name">{m.name}</span><span className="member-state">{meta.icon}</span></div>})}</div></button>})}</div></section><p className="calendar-footnote">인증일은 Asia/Seoul 기준 오전 4시에 바뀝니다. 날짜를 누르면 풀이와 인정량을 확인할 수 있습니다.</p></>;
  const statsView=<section className="stats-panel"><div className="stats-heading"><div><p className="eyebrow">MONTHLY REPORT</p><h2>{formatMonth(month)} 통계</h2></div><div className="stats-month-nav"><button className="nav-button" onClick={()=>void moveMonth(-1)}>‹</button><button className="nav-button" onClick={()=>void moveMonth(1)}>›</button></div></div><div className="stat-cards">{data.statistics.map(s=><article className="stat-card" key={s.userId}><div className="stat-card-head"><strong>{s.name}</strong>{s.userId===data.currentUserId&&<span className="me-badge">나</span>}</div><div className="stat-rate"><b>{s.completionRate}%</b><span>이번 달 인증률</span></div><div className="stat-grid"><div><span>완료</span><strong>{s.complete}</strong></div><div><span>미제출</span><strong>{s.missed}</strong></div><div><span>미루기</span><strong>{s.postponed}</strong></div><div><span>연속 인증</span><strong>{s.streak}일</strong></div></div><div className="stat-penalty"><span>누적 벌금</span><strong>{s.totalPenalty.toLocaleString()}원</strong></div></article>)}</div><GrowthStatsSection month={month} studyId={study.id} userId={data.currentUserId}/></section>;

  return<main className="app-shell"><header className="app-header"><div className="brand-block"><div className="brand-mark">🐹</div><div><p className="eyebrow">HAMJJUTER</p><h1>{study.name}</h1></div></div><div className="header-actions"><div className="app-tabs"><button className={tab==="calendar"?"active":""} onClick={()=>setTab("calendar")}>캘린더</button><button className={tab==="stats"?"active":""} onClick={()=>setTab("stats")}>통계</button></div><button className="icon-button" onClick={openSettings} aria-label="스터디 설정 열기">⚙</button></div></header>
  {needsRepository&&<section className="setup-banner"><div><span className="eyebrow">SETUP 2 / 2</span><strong>내 풀이 Repository를 연결하면 자동 인증이 시작됩니다.</strong><p>스터디 참여는 완료됐습니다. 이제 BaekjoonHub가 push하는 저장소만 골라주세요.</p></div><button className="primary-button" onClick={connect}>Repository 연결</button></section>}
  {showInstall&&<section className="install-banner"><div><strong>햄쮸터를 앱처럼 쓰기</strong><p>{iosInstall?"Safari에서 홈 화면에 추가하면 주소창 없이 바로 열립니다.":"홈 화면에 설치하면 다음부터 햄쮸터로 바로 들어올 수 있습니다."}</p></div><div><button className="secondary-button" onClick={()=>void installApp()}>{iosInstall?"설치 방법":"설치"}</button><button className="text-button" onClick={dismissInstall}>나중에</button></div></section>}
  {tab==="calendar"?calendarView:statsView}

  {detailOpen&&<div className="sheet-layer" onMouseDown={e=>{if(e.currentTarget===e.target)setDetailOpen(false)}}><aside className="side-sheet" role="dialog" aria-modal="true"><div className="sheet-header"><div><p className="eyebrow">DAILY DETAIL</p><h2>{formatDateHeading(selectedDate)}</h2><p>04:00 ~ 다음 날 03:59</p></div><button className="close-button" onClick={()=>setDetailOpen(false)}>×</button></div><div className="detail-members">{(selectedDay?.members??[]).filter(m=>m.state!=="inactive").map(m=>{const meta=STATE_META[m.state];return<section className="detail-member" key={m.userId}><div className="detail-member-heading"><div><strong>{m.name}</strong>{m.userId===data.currentUserId&&<span className="me-badge">나</span>}</div><span className={`state-label state-${m.state}`}>{meta.icon} {meta.label}</span></div>{m.submissions.length?<div className="submission-list">{m.submissions.map((s,i)=><div className="submission-row" key={`${s.problemId}-${s.solvedAt}-${i}`}><div><strong>{s.source==="manual"?`${PLATFORM_LABEL[s.platform as ManualPlatform]??s.platform} · ${s.difficulty}`:s.title}</strong><span>{s.source==="manual"?<>수동 인증 <em className="manual-badge">수동</em></>:<>{s.platform} {s.problemId} · {s.difficulty} · {formatTime(s.solvedAt)}</>}</span></div><b>+{s.credit.toFixed(2)}</b></div>)}</div>:<p className="empty-copy">이 날짜에 직접 기록된 풀이가 없습니다.</p>}<div className="credit-row"><span>직접 풀이 인정량</span><strong>{m.directCredits.toFixed(2)} / 1.00</strong></div>{m.state==="presolved"&&<p className="presolve-note">이전 풀이의 남은 인정량으로 미리 인증된 날짜입니다.</p>}{m.postponedAt&&<p className="postpone-note">{formatTime(m.postponedAt)} 미루기 신청</p>}{m.penalty>0&&<div className="penalty-row"><span>미제출 벌금</span><strong>{m.penalty.toLocaleString()}원</strong></div>}</section>})}
    {selectedDate<=data.studyDate&&<section className="manual-certification"><button className="manual-toggle" onClick={()=>setManualOpen(open=>!open)} aria-expanded={manualOpen}><span><strong>자동 인증이 안 됐나요?</strong><small>플랫폼 · 난이도 · 문제 수만 입력하면 됩니다.</small></span><b>{manualOpen?"−":"+ 수동 풀이 등록"}</b></button>{manualOpen&&<div className="manual-form"><label><span>플랫폼</span><select value={manualPlatform} onChange={e=>changeManualPlatform(e.target.value as ManualPlatform)}>{(Object.keys(PLATFORM_LABEL) as ManualPlatform[]).map(platform=><option value={platform} key={platform}>{PLATFORM_LABEL[platform]}</option>)}</select></label><label><span>난이도</span><select value={manualDifficulty} onChange={e=>setManualDifficulty(e.target.value)}>{MANUAL_DIFFICULTIES[manualPlatform].map(option=><option value={option.value} key={option.value}>{option.label}</option>)}</select></label><label><span>문제 수</span><input type="number" min={1} max={20} value={manualCount} onChange={e=>setManualCount(Math.max(1,Math.min(20,Number(e.target.value)||1)))}/></label><button className="primary-button full" onClick={()=>void addManualSubmission()} disabled={busy==="manual"}>{busy==="manual"?"등록 중…":`${manualCount}문제 등록`}</button><p>사진이나 문제 번호는 저장하지 않습니다. 본인 풀이만 수동으로 추가됩니다.</p></div>}</section>}
  </div>{selectedDate===data.studyDate&&mySelectedState?.state!=="postponed"&&<div className="sheet-actions"><button className="primary-button full" onClick={()=>void postpone()} disabled={busy==="postpone"}>{busy==="postpone"?"처리 중…":"오늘 미루기"}</button><p>미루기는 당일 {formatDeadline(study.postponeDeadlineHour,study.postponeDeadlineMinute)}까지, 연속 최대 {study.maxConsecutivePostpone}회 사용할 수 있습니다.</p></div>}</aside></div>}

  {settingsOpen&&<div className="sheet-layer" onMouseDown={e=>{if(e.currentTarget===e.target)setSettingsOpen(false)}}><aside className="side-sheet settings-sheet" role="dialog" aria-modal="true"><div className="sheet-header"><div><p className="eyebrow">STUDY SETTINGS</p><h2>스터디 설정</h2><p>스터디 참여원 누구나 함께 관리할 수 있습니다.</p></div><button className="close-button" onClick={()=>setSettingsOpen(false)}>×</button></div>
  <section className="settings-section"><div className="section-title"><div><h3>GitHub Repository</h3><p>BaekjoonHub가 push하는 알고리즘 저장소를 연결합니다.</p></div><button className="secondary-button" onClick={connect}>Repository 연결</button></div><div className="repository-list">{data.repositories.length?data.repositories.map(repo=><div className="repository-row" key={repo.id}><div><strong>{repo.fullName}</strong><span>자동 인증 연결됨</span></div><button className="text-button" onClick={()=>void backfill(repo)} disabled={busy===repo.id}>{busy===repo.id?"가져오는 중…":"과거 기록 가져오기"}</button></div>):<div className="settings-empty">아직 연결된 Repository가 없습니다.</div>}</div></section>
  <section className="settings-section"><div className="section-title"><div><h3>스터디 초대</h3><p>같이 인증할 사람에게 초대 링크를 공유하세요.</p></div></div><button className="copy-button" onClick={()=>void copyInvite()}><span>{`/join/${study.inviteCode}`}</span><strong>링크 복사</strong></button></section>
  <section className="settings-section rule-editor"><div className="section-title"><div><h3>인증 규칙</h3><p>참여원 누구나 수정할 수 있고 변경한 날짜부터 새 규칙이 적용됩니다.</p></div><span className="fixed-cutoff">Study Day 04:00 고정</span></div>
  <div className="rule-group"><h4>Baekjoon</h4><div className="rule-grid"><NumberField label="Bronze II~I" value={editableRules.ruleConfig.bojBronzeCount} min={1} suffix="문제" onChange={v=>setRulesDraft({...editableRules,ruleConfig:{...editableRules.ruleConfig,bojBronzeCount:v}})}/><NumberField label="Silver V~I" value={editableRules.ruleConfig.bojSilverCount} min={1} suffix="문제" onChange={v=>setRulesDraft({...editableRules,ruleConfig:{...editableRules.ruleConfig,bojSilverCount:v}})}/><NumberField label="Gold 이상" value={editableRules.ruleConfig.bojGoldCount} min={1} suffix="문제" onChange={v=>setRulesDraft({...editableRules,ruleConfig:{...editableRules.ruleConfig,bojGoldCount:v}})}/></div></div>
  <div className="rule-group"><h4>기타 플랫폼</h4><div className="rule-grid"><NumberField label="Programmers Lv.0~1" value={editableRules.ruleConfig.programmersLowCount} min={1} suffix="문제" onChange={v=>setRulesDraft({...editableRules,ruleConfig:{...editableRules.ruleConfig,programmersLowCount:v}})}/><NumberField label="Programmers Lv.2+" value={editableRules.ruleConfig.programmersHighCount} min={1} suffix="문제" onChange={v=>setRulesDraft({...editableRules,ruleConfig:{...editableRules.ruleConfig,programmersHighCount:v}})}/><NumberField label="SWEA D2~D3" value={editableRules.ruleConfig.sweaLowCount} min={1} suffix="문제" onChange={v=>setRulesDraft({...editableRules,ruleConfig:{...editableRules.ruleConfig,sweaLowCount:v}})}/><NumberField label="SWEA D4+" value={editableRules.ruleConfig.sweaHighCount} min={1} suffix="문제" onChange={v=>setRulesDraft({...editableRules,ruleConfig:{...editableRules.ruleConfig,sweaHighCount:v}})}/><NumberField label="CodeTree 삼성 기출" value={editableRules.ruleConfig.codetreeSamsungCount} min={1} suffix="문제" onChange={v=>setRulesDraft({...editableRules,ruleConfig:{...editableRules.ruleConfig,codetreeSamsungCount:v}})}/></div></div>
  <div className="rule-group"><h4>미루기 · 선풀이</h4><div className="rule-grid"><NumberField label="미루기 마감 시" value={editableRules.postponeDeadlineHour} max={23} suffix="시" onChange={v=>setRulesDraft({...editableRules,postponeDeadlineHour:v})}/><NumberField label="미루기 마감 분" value={editableRules.postponeDeadlineMinute} max={59} suffix="분" onChange={v=>setRulesDraft({...editableRules,postponeDeadlineMinute:v})}/><NumberField label="연속 미루기" value={editableRules.maxConsecutivePostpone} max={7} suffix="회" onChange={v=>setRulesDraft({...editableRules,maxConsecutivePostpone:v})}/><NumberField label="미리 풀기" value={editableRules.maxPresolveDays} max={14} suffix="일" onChange={v=>setRulesDraft({...editableRules,maxPresolveDays:v})}/></div></div>
  <div className="rule-group"><h4>미제출 벌금</h4><div className="rule-grid">{([1,2,3] as const).map(day=><NumberField key={day} label={`${day}일 연속`} value={editableRules.ruleConfig.penalties[day]} max={1000000} suffix="원" onChange={v=>setRulesDraft({...editableRules,ruleConfig:{...editableRules.ruleConfig,penalties:{...editableRules.ruleConfig.penalties,[day]:v}}})}/>)}</div></div><button className="primary-button full rules-save" onClick={()=>void saveRules()} disabled={busy==="rules"}>{busy==="rules"?"저장 중…":"인증 규칙 저장"}</button><p className="rule-warning">같은 Study Day에 다시 저장하면 그날의 최신 설정으로 이력이 갱신됩니다.</p></section>
  <section className="settings-section"><h3>규칙 변경 이력</h3><div className="history-list">{data.ruleHistory.length?data.ruleHistory.slice(0,8).map((h,i)=><div className="history-row" key={`${h.effectiveFrom}-${i}`}><strong>{h.effectiveFrom}</strong><span>{h.changedBy}</span></div>):<div className="settings-empty">아직 변경 이력이 없습니다.</div>}</div></section>
  <section className="settings-section account-section"><div><h3>계정</h3><p>직접 로그아웃하기 전까지 로그인 상태를 유지합니다.</p></div><button className="secondary-button danger-button" onClick={()=>void logout()}>로그아웃</button></section></aside></div>}
  {toast&&<div className="toast" role="status" aria-live="polite">{toast}</div>}</main>;
}
