"use client";

import { useEffect, useMemo, useState } from "react";
import { browserSupabase } from "@/lib/supabase-browser";

type Repo = { id: string; fullName: string };
type Submission = { platform: string; problemId: string; title: string; difficulty: string; credit: number; solvedAt: string };
type MemberState = "inactive" | "upcoming" | "presolved" | "complete" | "in-progress" | "postponed" | "missed";
type DayMember = { userId: string; name: string; state: MemberState; credits: number; directCredits: number; penalty: number; consecutiveMisses: number; postponedAt: string | null; submissions: Submission[] };
type CalendarDay = { date: string; members: DayMember[] };
type RuleConfig = {
  bojBronzeCount: number; bojSilverCount: number; bojGoldCount: number;
  programmersLowCount: number; programmersHighCount: number; sweaLowCount: number; sweaHighCount: number;
  codetreeSamsungCount: number; penalties: { 1: number; 2: number; 3: number };
};
type Study = {
  id: string; name: string; inviteCode: string; role: "admin" | "member"; rules: RuleConfig;
  postponeDeadlineHour: number; postponeDeadlineMinute: number; maxConsecutivePostpone: number; maxPresolveDays: number;
};
type MemberStat = { userId: string; name: string; complete: number; missed: number; postponed: number; totalPenalty: number; completionRate: number; streak: number };
type RuleHistory = { effectiveFrom: string; changedBy: string; createdAt: string | null };
type DashboardData = {
  study: Study | null; members: Array<{ userId: string; name: string }>; repositories: Repo[]; days: CalendarDay[];
  summary: { complete: number; postponed: number; missed: number; inProgress: number }; statistics: MemberStat[]; ruleHistory: RuleHistory[];
  currentUserId: string; studyDate: string; month: string;
};
type RulesDraft = { ruleConfig: RuleConfig; postponeDeadlineHour: number; postponeDeadlineMinute: number; maxConsecutivePostpone: number; maxPresolveDays: number };
type InstallPromptEvent = Event & { prompt: () => Promise<void>; userChoice: Promise<{ outcome: "accepted" | "dismissed" }> };

const STATE_META: Record<MemberState, { icon: string; label: string }> = {
  complete: { icon: "✅", label: "완료" }, presolved: { icon: "●", label: "선풀이" }, "in-progress": { icon: "🟡", label: "진행 중" },
  postponed: { icon: "⏭", label: "미루기" }, missed: { icon: "❌", label: "미제출" }, upcoming: { icon: "·", label: "예정" }, inactive: { icon: "", label: "참여 전" },
};
const WEEKDAYS = ["일", "월", "화", "수", "목", "금", "토"];

async function accessToken() { const { data } = await browserSupabase().auth.getSession(); return data.session?.access_token; }
function formatMonth(month: string) { const [year, value] = month.split("-"); return `${year}년 ${Number(value)}월`; }
function shiftMonth(month: string, delta: number) { const [year, value] = month.split("-").map(Number); const date = new Date(Date.UTC(year, value - 1 + delta, 1)); return `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, "0")}`; }
function formatDateHeading(date: string) { const parsed = new Date(`${date}T00:00:00Z`); const weekday = new Intl.DateTimeFormat("ko-KR", { weekday: "long", timeZone: "UTC" }).format(parsed); const [, month, day] = date.split("-"); return `${Number(month)}월 ${Number(day)}일 ${weekday}`; }
function formatTime(value: string | null) { if (!value) return ""; return new Intl.DateTimeFormat("ko-KR", { timeZone: "Asia/Seoul", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(value)); }
function formatDeadline(hour: number, minute: number) { return `${String(hour).padStart(2, "0")}:${String(minute).padStart(2, "0")}`; }
function calendarSlots(month: string) {
  const [year, monthNumber] = month.split("-").map(Number); const first = new Date(Date.UTC(year, monthNumber - 1, 1)); const firstWeekday = first.getUTCDay();
  const daysInMonth = new Date(Date.UTC(year, monthNumber, 0)).getUTCDate(); const slots: Array<{ date: string; currentMonth: boolean }> = [];
  for (let i = 0; i < 42; i += 1) { const dayNumber = i - firstWeekday + 1; const date = new Date(Date.UTC(year, monthNumber - 1, dayNumber)); slots.push({ date: date.toISOString().slice(0, 10), currentMonth: dayNumber >= 1 && dayNumber <= daysInMonth }); }
  return slots;
}
function cloneRules(study: Study): RulesDraft { return { ruleConfig: { ...study.rules, penalties: { ...study.rules.penalties } }, postponeDeadlineHour: study.postponeDeadlineHour, postponeDeadlineMinute: study.postponeDeadlineMinute, maxConsecutivePostpone: study.maxConsecutivePostpone, maxPresolveDays: study.maxPresolveDays }; }
function NumberField({ label, value, min = 0, max = 20, suffix, onChange }: { label: string; value: number; min?: number; max?: number; suffix: string; onChange: (value: number) => void }) {
  return <label className="rule-field"><span>{label}</span><div><input type="number" min={min} max={max} value={value} onChange={(event) => onChange(Number(event.target.value))} /><em>{suffix}</em></div></label>;
}

export function Dashboard({ githubAppSlug }: { githubAppSlug: string }) {
  const [data, setData] = useState<DashboardData | null>(null);
  const [error, setError] = useState(""); const [busy, setBusy] = useState(""); const [month, setMonth] = useState(""); const [selectedDate, setSelectedDate] = useState("");
  const [settingsOpen, setSettingsOpen] = useState(false); const [detailOpen, setDetailOpen] = useState(false); const [rulesDraft, setRulesDraft] = useState<RulesDraft | null>(null);
  const [toast, setToast] = useState(""); const [tab, setTab] = useState<"calendar" | "stats">("calendar"); const [calendarMode, setCalendarMode] = useState<"month" | "week">("month");
  const [joinCode, setJoinCode] = useState(""); const [installPrompt, setInstallPrompt] = useState<InstallPromptEvent | null>(null); const [showInstall, setShowInstall] = useState(false); const [iosInstall, setIosInstall] = useState(false);

  async function reload(targetMonth?: string) {
    const access = await accessToken(); if (!access) { window.location.replace("/"); return; }
    const query = targetMonth ? `?month=${encodeURIComponent(targetMonth)}` : ""; const response = await fetch(`/api/dashboard${query}`, { headers: { Authorization: `Bearer ${access}` } });
    const payload = await response.json() as DashboardData & { error?: string }; if (!response.ok) { setError(payload.error ?? "조회 실패"); return; }
    setError(""); setData(payload); setMonth(payload.month); if (!selectedDate || !selectedDate.startsWith(payload.month)) setSelectedDate(payload.studyDate.startsWith(payload.month) ? payload.studyDate : `${payload.month}-01`);
  }

  useEffect(() => { let cancelled = false; void (async () => { const access = await accessToken(); if (!access) { window.location.replace("/"); return; } const response = await fetch("/api/dashboard", { headers: { Authorization: `Bearer ${access}` } }); const payload = await response.json() as DashboardData & { error?: string }; if (cancelled) return; if (!response.ok) { setError(payload.error ?? "조회 실패"); return; } setData(payload); setMonth(payload.month); setSelectedDate(payload.studyDate.startsWith(payload.month) ? payload.studyDate : `${payload.month}-01`); })(); return () => { cancelled = true; }; }, []);
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(""), 2800); return () => window.clearTimeout(timer); }, [toast]);
  useEffect(() => { function closeOnEscape(event: KeyboardEvent) { if (event.key === "Escape") { setDetailOpen(false); setSettingsOpen(false); } } window.addEventListener("keydown", closeOnEscape); return () => window.removeEventListener("keydown", closeOnEscape); }, []);
  useEffect(() => {
    const standalone = window.matchMedia("(display-mode: standalone)").matches || Boolean((navigator as Navigator & { standalone?: boolean }).standalone);
    if (standalone || localStorage.getItem("hamster-install-dismissed") === "1") return;
    const ios = /iphone|ipad|ipod/i.test(navigator.userAgent);
    setIosInstall(ios); if (ios) setShowInstall(true);
    const handler = (event: Event) => { event.preventDefault(); setInstallPrompt(event as InstallPromptEvent); setShowInstall(true); };
    window.addEventListener("beforeinstallprompt", handler); return () => window.removeEventListener("beforeinstallprompt", handler);
  }, []);

  async function createStudy() { setBusy("create"); const access = await accessToken(); const response = await fetch("/api/studies", { method: "POST", headers: { Authorization: `Bearer ${access}`, "Content-Type": "application/json" }, body: JSON.stringify({ name: "햄쮸터" }) }); setBusy(""); if (response.ok) await reload(); else setToast("스터디를 만들지 못했습니다."); }
  async function joinStudy() { if (!joinCode.trim()) return; setBusy("join"); const access = await accessToken(); const response = await fetch("/api/studies/join", { method: "POST", headers: { Authorization: `Bearer ${access}`, "Content-Type": "application/json" }, body: JSON.stringify({ code: joinCode.trim() }) }); const payload = await response.json() as { error?: string }; setBusy(""); if (!response.ok) setToast(payload.error ?? "스터디 참여에 실패했습니다."); else await reload(); }
  function openSettings() { if (data?.study) setRulesDraft(cloneRules(data.study)); setSettingsOpen(true); }
  function connect() { if (!data?.study) return; if (!githubAppSlug) { setToast("GitHub App 설정이 아직 연결되지 않았습니다."); return; } localStorage.setItem("hamster-study-id", data.study.id); window.location.href = `https://github.com/apps/${githubAppSlug}/installations/new`; }
  async function postpone() { if (!data?.study || selectedDate !== data.studyDate) return; setBusy("postpone"); const access = await accessToken(); const response = await fetch("/api/postponements", { method: "POST", headers: { Authorization: `Bearer ${access}`, "Content-Type": "application/json" }, body: JSON.stringify({ studyId: data.study.id }) }); const payload = await response.json() as { error?: string; duplicate?: boolean }; setBusy(""); if (!response.ok) setToast(payload.error ?? "미루기 신청에 실패했습니다."); else { setToast(payload.duplicate ? "이미 오늘 미루기를 신청했습니다." : "오늘 미루기를 적용했습니다."); await reload(month); } }
  async function backfill(repo: Repo) { setBusy(repo.id); const access = await accessToken(); const response = await fetch("/api/repositories/backfill", { method: "POST", headers: { Authorization: `Bearer ${access}`, "Content-Type": "application/json" }, body: JSON.stringify({ connectionId: repo.id }) }); const payload = await response.json() as { error?: string; inserted?: number }; setBusy(""); if (!response.ok) setToast(payload.error ?? "과거 기록을 가져오지 못했습니다."); else { setToast(`${payload.inserted ?? 0}개 풀이를 가져왔습니다.`); await reload(month); } }
  async function saveRules() { if (!data?.study || !rulesDraft) return; setBusy("rules"); const access = await accessToken(); const response = await fetch("/api/studies/settings", { method: "PATCH", headers: { Authorization: `Bearer ${access}`, "Content-Type": "application/json" }, body: JSON.stringify({ studyId: data.study.id, ...rulesDraft }) }); const payload = await response.json() as { error?: string; effectiveFrom?: string }; setBusy(""); if (!response.ok) { setToast(payload.error ?? "규칙을 저장하지 못했습니다."); return; } setToast(`${payload.effectiveFrom ?? "오늘"}부터 새 규칙을 적용합니다.`); await reload(month); }
  async function copyInvite() { if (!data?.study) return; const invite = `${window.location.origin}/join/${data.study.inviteCode}`; await navigator.clipboard.writeText(invite); setToast("초대 링크를 복사했습니다."); }
  async function logout() { await browserSupabase().auth.signOut(); localStorage.removeItem("hamster-study-id"); window.location.replace("/"); }
  async function moveMonth(delta: number) { const next = shiftMonth(month, delta); setDetailOpen(false); await reload(next); }
  async function goToday() { if (!data) return; const todayMonth = data.studyDate.slice(0, 7); await reload(todayMonth); setSelectedDate(data.studyDate); setDetailOpen(true); }
  async function openDate(date: string, currentMonth: boolean) { if (!currentMonth) await reload(date.slice(0, 7)); setSelectedDate(date); setDetailOpen(true); }
  async function installApp() { if (installPrompt) { await installPrompt.prompt(); const choice = await installPrompt.userChoice; if (choice.outcome === "accepted") setShowInstall(false); } else if (iosInstall) setToast("Safari 공유 버튼 → 홈 화면에 추가 → 웹 앱으로 열기를 선택하세요."); }
  function dismissInstall() { localStorage.setItem("hamster-install-dismissed", "1"); setShowInstall(false); }

  const dayByDate = useMemo(() => new Map((data?.days ?? []).map((day) => [day.date, day])), [data]);
  const slots = useMemo(() => (month ? calendarSlots(month) : []), [month]);
  const visibleSlots = useMemo(() => { if (calendarMode === "month" || !selectedDate) return slots; const index = slots.findIndex((slot) => slot.date === selectedDate); const start = index < 0 ? 0 : Math.floor(index / 7) * 7; return slots.slice(start, start + 7); }, [calendarMode, selectedDate, slots]);
  const selectedDay = selectedDate ? dayByDate.get(selectedDate) : undefined; const mySelectedState = selectedDay?.members.find((member) => member.userId === data?.currentUserId);

  if (error) return <main className="app-shell"><div className="empty-state"><strong>대시보드를 불러오지 못했습니다.</strong><p>{error}</p><button className="secondary-button" onClick={() => void reload(month)}>다시 시도</button></div></main>;
  if (!data) return <main className="app-shell"><div className="loading-state">햄쮸터를 불러오는 중…</div></main>;
  if (!data.study) return <main className="app-shell"><section className="onboarding onboarding-card"><span className="eyebrow">WELCOME TO HAMJJUTER</span><h1>스터디만 고르면<br />자동 인증 준비 끝.</h1><p>새 스터디를 만들거나 받은 초대 코드로 바로 참여할 수 있습니다.</p><div className="onboarding-actions"><button className="primary-button" onClick={() => void createStudy()} disabled={busy === "create"}>{busy === "create" ? "만드는 중…" : "새 스터디 만들기"}</button><div className="join-box"><input value={joinCode} onChange={(event) => setJoinCode(event.target.value)} placeholder="초대 코드 입력" aria-label="스터디 초대 코드" /><button className="secondary-button" onClick={() => void joinStudy()} disabled={busy === "join"}>{busy === "join" ? "참여 중…" : "참여하기"}</button></div></div></section></main>;

  const study = data.study; const editableRules = rulesDraft ?? cloneRules(study); const needsRepository = data.repositories.length === 0;

  return <main className="app-shell">
    <header className="app-header"><div className="brand-block"><div className="brand-mark" aria-hidden="true">🐹</div><div><p className="eyebrow">HAMJJUTER</p><h1>{study.name}</h1></div></div><div className="header-actions"><div className="app-tabs" role="tablist"><button className={tab === "calendar" ? "active" : ""} onClick={() => setTab("calendar")}>캘린더</button><button className={tab === "stats" ? "active" : ""} onClick={() => setTab("stats")}>통계</button></div><button className="icon-button" onClick={openSettings} aria-label="스터디 설정 열기" title="스터디 설정">⚙</button></div></header>

    {needsRepository && <section className="setup-banner"><div><span className="eyebrow">SETUP 2 / 2</span><strong>내 풀이 Repository를 연결하면 자동 인증이 시작됩니다.</strong><p>스터디 참여는 완료됐습니다. 이제 BaekjoonHub가 push하는 저장소만 골라주세요.</p></div><button className="primary-button" onClick={connect}>Repository 연결</button></section>}
    {showInstall && <section className="install-banner"><div><strong>햄쮸터를 앱처럼 쓰기</strong><p>{iosInstall ? "Safari에서 홈 화면에 추가하면 주소창 없이 바로 열립니다." : "홈 화면에 설치하면 다음부터 햄쮸터로 바로 들어올 수 있습니다."}</p></div><div><button className="secondary-button" onClick={() => void installApp()}>{iosInstall ? "설치 방법" : "설치"}</button><button className="text-button" onClick={dismissInstall}>나중에</button></div></section>}

    {tab === "calendar" ? <>
      <section className="calendar-toolbar" aria-label="캘린더 탐색"><div className="month-navigation"><button className="nav-button" onClick={() => void moveMonth(-1)} aria-label="이전 달">‹</button><h2>{formatMonth(month)}</h2><button className="nav-button" onClick={() => void moveMonth(1)} aria-label="다음 달">›</button><button className="today-button" onClick={() => void goToday()}>오늘</button><div className="view-toggle"><button className={calendarMode === "week" ? "active" : ""} onClick={() => setCalendarMode("week")}>주</button><button className={calendarMode === "month" ? "active" : ""} onClick={() => setCalendarMode("month")}>월</button></div></div><div className="summary-strip"><span><strong>{data.members.length}</strong>명</span><span><strong>{data.summary.complete}</strong> 완료</span><span><strong>{data.summary.postponed}</strong> 미루기</span><span><strong>{data.summary.missed}</strong> 미제출</span></div></section>
      <section className={`calendar-card mode-${calendarMode}`} aria-label={`${formatMonth(month)} 인증 캘린더`}><div className="weekday-row" aria-hidden="true">{WEEKDAYS.map((day) => <div key={day}>{day}</div>)}</div><div className="calendar-grid">{visibleSlots.map((slot) => { const day = dayByDate.get(slot.date); const isToday = slot.date === data.studyDate; const isSelected = slot.date === selectedDate; return <button key={slot.date} className={`calendar-day${slot.currentMonth ? "" : " is-adjacent"}${isToday ? " is-today" : ""}${isSelected ? " is-selected" : ""}`} onClick={() => void openDate(slot.date, slot.currentMonth)} aria-pressed={isSelected}><div className="day-heading"><span>{Number(slot.date.slice(-2))}</span>{isToday && <em>오늘</em>}</div><div className="day-members">{(day?.members ?? []).filter((member) => member.state !== "inactive").map((member) => { const meta = STATE_META[member.state]; return <div key={member.userId} className={`member-chip state-${member.state}`} title={`${member.name} · ${meta.label}`}><span className="member-name">{member.name}</span><span className="member-state" aria-label={meta.label}>{meta.icon}</span></div>; })}</div></button>; })}</div></section>
      <p className="calendar-footnote">인증일은 Asia/Seoul 기준 오전 4시에 바뀝니다. 날짜를 누르면 풀이와 인정량을 확인할 수 있습니다.</p>
    </> : <section className="stats-panel"><div className="stats-heading"><div><p className="eyebrow">MONTHLY REPORT</p><h2>{formatMonth(month)} 통계</h2></div><div className="stats-month-nav"><button className="nav-button" onClick={() => void moveMonth(-1)}>‹</button><button className="nav-button" onClick={() => void moveMonth(1)}>›</button></div></div><div className="stat-cards">{data.statistics.map((item) => <article className="stat-card" key={item.userId}><div className="stat-card-head"><strong>{item.name}</strong>{item.userId === data.currentUserId && <span className="me-badge">나</span>}</div><div className="stat-rate"><b>{item.completionRate}%</b><span>이번 달 인증률</span></div><div className="stat-grid"><div><span>완료</span><strong>{item.complete}</strong></div><div><span>미제출</span><strong>{item.missed}</strong></div><div><span>미루기</span><strong>{item.postponed}</strong></div><div><span>연속 인증</span><strong>{item.streak}일</strong></div></div><div className="stat-penalty"><span>누적 벌금</span><strong>{item.totalPenalty.toLocaleString()}원</strong></div></article>)}</div></section>}

    {detailOpen && <div className="sheet-layer" onMouseDown={(event) => { if (event.currentTarget === event.target) setDetailOpen(false); }}><aside className="side-sheet" role="dialog" aria-modal="true" aria-label="날짜별 인증 상세"><div className="sheet-header"><div><p className="eyebrow">DAILY DETAIL</p><h2>{formatDateHeading(selectedDate)}</h2><p>04:00 ~ 다음 날 03:59</p></div><button className="close-button" onClick={() => setDetailOpen(false)} aria-label="상세 닫기">×</button></div><div className="detail-members">{(selectedDay?.members ?? []).filter((member) => member.state !== "inactive").map((member) => { const meta = STATE_META[member.state]; return <section className="detail-member" key={member.userId}><div className="detail-member-heading"><div><strong>{member.name}</strong>{member.userId === data.currentUserId && <span className="me-badge">나</span>}</div><span className={`state-label state-${member.state}`}>{meta.icon} {meta.label}</span></div>{member.submissions.length > 0 ? <div className="submission-list">{member.submissions.map((submission, index) => <div className="submission-row" key={`${submission.problemId}-${submission.solvedAt}-${index}`}><div><strong>{submission.title}</strong><span>{submission.platform} {submission.problemId} · {submission.difficulty} · {formatTime(submission.solvedAt)}</span></div><b>+{submission.credit.toFixed(2)}</b></div>)}</div> : <p className="empty-copy">이 날짜에 직접 기록된 풀이가 없습니다.</p>}<div className="credit-row"><span>직접 풀이 인정량</span><strong>{member.directCredits.toFixed(2)} / 1.00</strong></div>{member.state === "presolved" && <p className="presolve-note">이전 풀이의 남은 인정량으로 미리 인증된 날짜입니다.</p>}{member.postponedAt && <p className="postpone-note">{formatTime(member.postponedAt)} 미루기 신청</p>}{member.penalty > 0 && <div className="penalty-row"><span>미제출 벌금</span><strong>{member.penalty.toLocaleString()}원</strong></div>}</section>; })}</div>{selectedDate === data.studyDate && mySelectedState?.state !== "postponed" && <div className="sheet-actions"><button className="primary-button full" onClick={() => void postpone()} disabled={busy === "postpone"}>{busy === "postpone" ? "처리 중…" : "오늘 미루기"}</button><p>미루기는 당일 {formatDeadline(study.postponeDeadlineHour, study.postponeDeadlineMinute)}까지, 연속 최대 {study.maxConsecutivePostpone}회 사용할 수 있습니다.</p></div>}</aside></div>}

    {settingsOpen && <div className="sheet-layer" onMouseDown={(event) => { if (event.currentTarget === event.target) setSettingsOpen(false); }}><aside className="side-sheet settings-sheet" role="dialog" aria-modal="true" aria-label="스터디 설정"><div className="sheet-header"><div><p className="eyebrow">STUDY SETTINGS</p><h2>스터디 설정</h2><p>스터디 참여원 누구나 함께 관리할 수 있습니다.</p></div><button className="close-button" onClick={() => setSettingsOpen(false)} aria-label="설정 닫기">×</button></div>
      <section className="settings-section"><div className="section-title"><div><h3>GitHub Repository</h3><p>BaekjoonHub가 push하는 알고리즘 저장소를 연결합니다.</p></div><button className="secondary-button" onClick={connect}>Repository 연결</button></div><div className="repository-list">{data.repositories.length ? data.repositories.map((repo) => <div className="repository-row" key={repo.id}><div><strong>{repo.fullName}</strong><span>자동 인증 연결됨</span></div><button className="text-button" onClick={() => void backfill(repo)} disabled={busy === repo.id}>{busy === repo.id ? "가져오는 중…" : "과거 기록 가져오기"}</button></div>) : <div className="settings-empty">아직 연결된 Repository가 없습니다.</div>}</div></section>
      <section className="settings-section"><div className="section-title"><div><h3>스터디 초대</h3><p>같이 인증할 사람에게 초대 링크를 공유하세요.</p></div></div><button className="copy-button" onClick={() => void copyInvite()}><span>{`/join/${study.inviteCode}`}</span><strong>링크 복사</strong></button></section>
      <section className="settings-section rule-editor"><div className="section-title"><div><h3>인증 규칙</h3><p>참여원 누구나 수정할 수 있고 변경한 날짜부터 새 규칙이 적용됩니다.</p></div><span className="fixed-cutoff">Study Day 04:00 고정</span></div><div className="rule-group"><h4>Baekjoon</h4><div className="rule-grid"><NumberField label="Bronze II~I" value={editableRules.ruleConfig.bojBronzeCount} min={1} suffix="문제" onChange={(value) => setRulesDraft({ ...editableRules, ruleConfig: { ...editableRules.ruleConfig, bojBronzeCount: value } })} /><NumberField label="Silver V~I" value={editableRules.ruleConfig.bojSilverCount} min={1} suffix="문제" onChange={(value) => setRulesDraft({ ...editableRules, ruleConfig: { ...editableRules.ruleConfig, bojSilverCount: value } })} /><NumberField label="Gold 이상" value={editableRules.ruleConfig.bojGoldCount} min={1} suffix="문제" onChange={(value) => setRulesDraft({ ...editableRules, ruleConfig: { ...editableRules.ruleConfig, bojGoldCount: value } })} /></div></div>
      <div className="rule-group"><h4>기타 플랫폼</h4><div className="rule-grid"><NumberField label="Programmers Lv.0~1" value={editableRules.ruleConfig.programmersLowCount} min={1} suffix="문제" onChange={(value) => setRulesDraft({ ...editableRules, ruleConfig: { ...editableRules.ruleConfig, programmersLowCount: value } })} /><NumberField label="Programmers Lv.2+" value={editableRules.ruleConfig.programmersHighCount} min={1} suffix="문제" onChange={(value) => setRulesDraft({ ...editableRules, ruleConfig: { ...editableRules.ruleConfig, programmersHighCount: value } })} /><NumberField label="SWEA D2~D3" value={editableRules.ruleConfig.sweaLowCount} min={1} suffix="문제" onChange={(value) => setRulesDraft({ ...editableRules, ruleConfig: { ...editableRules.ruleConfig, sweaLowCount: value } })} /><NumberField label="SWEA D4+" value={editableRules.ruleConfig.sweaHighCount} min={1} suffix="문제" onChange={(value) => setRulesDraft({ ...editableRules, ruleConfig: { ...editableRules.ruleConfig, sweaHighCount: value } })} /><NumberField label="CodeTree 삼성 기출" value={editableRules.ruleConfig.codetreeSamsungCount} min={1} suffix="문제" onChange={(value) => setRulesDraft({ ...editableRules, ruleConfig: { ...editableRules.ruleConfig, codetreeSamsungCount: value } })} /></div></div>
      <div className="rule-group"><h4>미루기 · 선풀이</h4><div className="rule-grid"><NumberField label="미루기 마감 시" value={editableRules.postponeDeadlineHour} max={23} suffix="시" onChange={(value) => setRulesDraft({ ...editableRules, postponeDeadlineHour: value })} /><NumberField label="미루기 마감 분" value={editableRules.postponeDeadlineMinute} max={59} suffix="분" onChange={(value) => setRulesDraft({ ...editableRules, postponeDeadlineMinute: value })} /><NumberField label="연속 미루기" value={editableRules.maxConsecutivePostpone} max={7} suffix="회" onChange={(value) => setRulesDraft({ ...editableRules, maxConsecutivePostpone: value })} /><NumberField label="미리 풀기" value={editableRules.maxPresolveDays} max={14} suffix="일" onChange={(value) => setRulesDraft({ ...editableRules, maxPresolveDays: value })} /></div></div>
      <div className="rule-group"><h4>미제출 벌금</h4><div className="rule-grid"><NumberField label="1일 연속" value={editableRules.ruleConfig.penalties[1]} max={1000000} suffix="원" onChange={(value) => setRulesDraft({ ...editableRules, ruleConfig: { ...editableRules.ruleConfig, penalties: { ...editableRules.ruleConfig.penalties, 1: value } } })} /><NumberField label="2일 연속" value={editableRules.ruleConfig.penalties[2]} max={1000000} suffix="원" onChange={(value) => setRulesDraft({ ...editableRules, ruleConfig: { ...editableRules.ruleConfig, penalties: { ...editableRules.ruleConfig.penalties, 2: value } } })} /><NumberField label="3일 연속" value={editableRules.ruleConfig.penalties[3]} max={1000000} suffix="원" onChange={(value) => setRulesDraft({ ...editableRules, ruleConfig: { ...editableRules.ruleConfig, penalties: { ...editableRules.ruleConfig.penalties, 3: value } } })} /></div></div><button className="primary-button full rules-save" onClick={() => void saveRules()} disabled={busy === "rules"}>{busy === "rules" ? "저장 중…" : "인증 규칙 저장"}</button><p className="rule-warning">같은 Study Day에 다시 저장하면 그날의 최신 설정으로 이력이 갱신됩니다.</p></section>
      <section className="settings-section"><h3>규칙 변경 이력</h3><div className="history-list">{data.ruleHistory.length ? data.ruleHistory.slice(0, 8).map((item, index) => <div className="history-row" key={`${item.effectiveFrom}-${index}`}><strong>{item.effectiveFrom}</strong><span>{item.changedBy}</span></div>) : <div className="settings-empty">아직 변경 이력이 없습니다.</div>}</div></section>
      <section className="settings-section account-section"><div><h3>계정</h3><p>직접 로그아웃하기 전까지 로그인 상태를 유지합니다.</p></div><button className="secondary-button danger-button" onClick={() => void logout()}>로그아웃</button></section>
    </aside></div>}

    {toast && <div className="toast" role="status" aria-live="polite">{toast}</div>}
  </main>;
}
